from typing import Dict

import pytest


@pytest.fixture
def proteinSequences() -> Dict[str, str]:
    """Dictionary of UniProt identifiers to protein sequences for two isoforms of Q86U42.

    Returns:
        Dict[str, str]: dictionary of UniProt identifiers to protein sequences
    """
    proteinSequences = dict()
    proteinSequences["Q86U42"] = (
        "MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDYGNGLESEELEPEELLLEPEPEPEPEEEPPRPRAPPGAPGPGPGSGAPGSQEEEEEPGL"
        "VEGDPGDGAIEDPELEAIKARVREMEEEAEKLKELQNEVEKQMNMSPPPGNAGPVIMSIEEKMEADARSIYVGNVDYGATAEELEAHFHGCGSVNRVTILCDKF"
        "SGHPKGFAYIEFSDKESVRTSLALDESLFRGRQIKVIPKRTNRPGISTTDRGFPRARYRARTTNYNSSRSRFYSGFNSRPRGRVYRGRARATSWYSPY"
    )
    proteinSequences["Q86U42-2"] = (
        "MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDYGNGLESEELEPEELLLEPEPEPEPEEEPPRPRAPPGAPGPGPGSGAPGSQEEEEEPGL"
        "VEGDPGDGAIEDPELEAIKARVREMEEEAEKLKELQNEVEKQMNMSPPPGNAGPVIMSIEEKMEADARSIYVGNVDYGATAEELEAHFHGCGSVNRVTILCDKF"
        "SGHPKGFAYIEFSDKESVRTSLALDESLFRGRQIKVIPKRTNRPGISTTDRGFPRARYRARTTNYNSSRSRFYSGFNSRPRGRVYRSG"
    )
    return proteinSequences


@pytest.fixture
def proteinSequencesExtraPhospho() -> Dict[str, str]:
    """Dictionary of UniProt identifiers to protein sequences for two isoforms of Q86U42 with 2 extra potential p-sites.

    Returns:
        Dict[str, str]: dictionary of UniProt identifiers to protein sequences
    """
    proteinSequences = dict()
    proteinSequences["Q86U42"] = (
        "MAAAAAAAAAAGAAGGRGSTYGPGRRRHLVPGAGGEAGEGAPGGAGDYGNGLESEELEPEELLLEPEPEPEPEEEPPRPRAPPGAPGPGPGSGAPGSQEEEEEPGL"
        "VEGDPGDGAIEDPELEAIKARVREMEEEAEKLKELQNEVEKQMNMSPPPGNAGPVIMSIEEKMEADARSIYVGNVDYGATAEELEAHFHGCGSVNRVTILCDKF"
        "SGHPKGFAYIEFSDKESVRTSLALDESLFRGRQIKVIPKRTNRPGISTTDRGFPRARYRARTTNYNSSRSRFYSGFNSRPRGRVYRGRARATSWYSPY"
    )
    proteinSequences["Q86U42-2"] = (
        "MAAAAAAAAAAGAAGGRGSTYGPGRRRHLVPGAGGEAGEGAPGGAGDYGNGLESEELEPEELLLEPEPEPEPEEEPPRPRAPPGAPGPGPGSGAPGSQEEEEEPGL"
        "VEGDPGDGAIEDPELEAIKARVREMEEEAEKLKELQNEVEKQMNMSPPPGNAGPVIMSIEEKMEADARSIYVGNVDYGATAEELEAHFHGCGSVNRVTILCDKF"
        "SGHPKGFAYIEFSDKESVRTSLALDESLFRGRQIKVIPKRTNRPGISTTDRGFPRARYRARTTNYNSSRSRFYSGFNSRPRGRVYRSG"
    )
    return proteinSequences
